image: node:latest

stages:
  - install
  - build

install:
  stage: install
  script:
    - cd frontend
    - npm install
  cache:
    paths:
      - frontend/node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - frontend/node_modules/

build:
  stage: build
  dependencies:
    - install
  script:
    - cd frontend
    - npm run-script build
